### PR TITLE
Log file to record client errors

### LINKED ISSUE #985: Log file to record client errors
Like language server logs, vscode-java can have a log file to record errors that happen at the client side.

Currently, users have to open the console to extract the logs as described in https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting#get-the-vscode-java-logs

This can be improved by having a command "Java: Show language client log file" to make it easier and increase the possibility that users correctly provide the logs inside issues.

#782 can be improved by having log files.

### PR DESCRIPTION
**Pull request by akaroml**
Signed-off-by: Rome Li <rome.li@microsoft.com>
Fix #985

### CODE REVIEW

**Comment by fbricon** [comment]
You mentioned a command to open the client log file

**Comment by fbricon** [comment]
superseded by #988

**Comment by akaroml** [comment]
Great. It's in!

**Comment by akaroml** [comment]
Uhh... I just checked #988. There is one improvement we can make. I'll comment on the new PR.

**Pull request closed without merging**
