### PR TITLE
Remove vulnerable dependencies.

### PR DESCRIPTION
**Pull request by fbricon**
Download server task is no longer needed

### CODE REVIEW

**Comment by snjeza** [comment]
```
npm run build-server
```
returns the following error:

```
...
[INFO] Reactor Summary for JDT Language Server :: Parent 0.53.0-SNAPSHOT:
[INFO] 
[INFO] JDT Language Server :: Parent ...................... SUCCESS [  0.071 s]
[INFO] JDT Language Server :: Target Platform ............. SUCCESS [  0.192 s]
[INFO] JDT Language Server :: Core ........................ SUCCESS [  9.022 s]
[INFO] JDT Language Server :: Tests ....................... SUCCESS [  2.363 s]
[INFO] JDT Language Server :: Product ..................... SUCCESS [ 12.594 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  50.134 s
[INFO] Finished at: 2020-03-23T16:46:26+01:00
[INFO] ------------------------------------------------------------------------
[16:46:27] 'build_server' errored after 52 s
[16:46:27] ReferenceError: decompress is not defined
    at /home/snjeza/projects/vscode-java/gulpfile.js:9:3
    at taskWrapper (/home/snjeza/projects/vscode-java/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (/home/snjeza/projects/vscode-java/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! java@0.59.0 build-server: `gulp build_server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the java@0.59.0 build-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/snjeza/.npm/_logs/2020-03-23T15_46_27_255Z-debug.log
```

**Comment by fbricon** [comment]
Wow that's embarrassing! 
double-facepalm

decompress has no fix yet, so I'll start by removing what I can.

**Comment by fbricon** [comment]
@snjeza updated

**Comment by snjeza** [comment]
test this please

**Comment by fbricon** [comment]
Abandoning as vulnerable dependencies have already been updated, download server task is actually used/referenced in the contributing guide, for those who don't want/need to build the server locally.

**Pull request closed without merging**
