### PR TITLE
Add support for surround with try_catch.

### LINKED ISSUE #3103: Add support for Surround with TryCatch for Runtime Exceptions
Take the following code example and try to invoke Surround with Snippet, I would expect try catch snippet which will allow me to select the Exception types provided by jdt.ls which are thrown by the foo() method according to jdt.ls completion rules.

```
public class App {

  public void foo() throws IllegalStateException {
  }

  public static void main(String[] args) {
     foo();
  }
```
##### Environment
- Operating System: Any
- JDK version: Any
- Visual Studio Code version: Any
- Java extension version: Any

### PR DESCRIPTION
**Pull request by gayanper**
The following changeset add a new snippet which will only available under Surround With Snippets for provide a try catch block surrounding the selected text.

### CODE REVIEW

**Comment by gayanper** [comment]
@jdneo @testforstephen @rgrunber Let me know what you think

**Comment by rgrunber** [comment]
Is there a reason to not have this on the language server side, similar to https://github.com/redhat-developer/vscode-java/issues/2128 ? Currently we have our own copy of https://github.com/eclipse/eclipse.jdt.ls/blob/f32c0f6275d1cdec241e086841c8627010c2f714/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/corext/refactoring/surround/SurroundWithTryCatchRefactoring.java (maybe we could even move it into jdt.core.manipulation from ui ?), but we only use it when there's a diagnostic that requires using try/catch. We could maybe open it up (like in JDT UI) to an arbitrary selection.

**Comment by gayanper** [comment]
@rgrunber Please check the new patch, it work both with and without selection.

**Review by rgrunber — APPROVED** [review]
With this change, the `try_catch` snippet shows up in the `Surround With Snippet` menu. It can probably be customized for easier access with a keybinding. The snippet continues to work as before when just accessed from a completion item.

surround-with-try-catch-snippet

I was thinking of adding it to `try_resources` but that has the added complication of whether the selected code represents the resource statement, or the body. So we can leave it for now.

**Pull request merged**
