### PR TITLE
Fix extension loading #3005

### PR DESCRIPTION
**Pull request by gayanper**

### CODE REVIEW

**Comment by gayanper** [comment]
@rgrunber @jdneo Let me know if there is another way to solve this

**Comment by snjeza** [comment]
The issue happens when setting `java.jdt.ls.java.home`.
The PR fixes it.

**Review by snjeza — APPROVED** [review]

**Comment by fbricon** [comment]
can anyone explain why this patch fixes the issue? It seems wrong, but I suck at JS/TS

**Comment by gayanper** [comment]
I'm not an expert either, but i guess it could be something to do with how import and require load the JS module. 

I doubt if it could be due to a recent electron + NodeJS runtime change.

**Comment by CsCherrYY** [comment]
> can anyone explain why this patch fixes the issue? It seems wrong, but I suck at JS/TS

This issue should be related to the config change of #2967, this PR introduces some project configurations related to webview (react) might be incompatible with existing statements.

I created a new PR for this #3009 , which might resolve this issue and avoid any potential issue in the future

**Comment by jdneo** [comment]
To add more information: https://www.typescriptlang.org/tsconfig#esModuleInterop

**Comment by jdneo** [comment]
With https://github.com/redhat-developer/vscode-java/pull/3009, we can close this PR.

**Pull request closed without merging**
