### PR TITLE
Migrate to 'vscode-test'

### LINKED ISSUE #977: replace package vscode with @types/vscode
npm package `vscode` is deprecating. See: [v1.36 release note](https://code.visualstudio.com/updates/v1_36#_splitting-vscode-package-into-typesvscode-and-vscodetest)
Suggest to follow [migration guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode)  to use `@types/vscode` instead of `vscode`

### PR DESCRIPTION
**Pull request by akaroml**
Signed-off-by: Rome Li <rome.li@microsoft.com>
Fix #977

### CODE REVIEW

**Comment by fbricon** [comment]
@akaroml Can you please fix the conflicts?

**Comment by akaroml** [comment]
> @akaroml Can you please fix the conflicts?

Fixed!

**Comment by akaroml** [comment]
test this please

**Comment by akaroml** [comment]
Just looked into the test log and it seemed to fail completely on the build server. I'll investigate next week.

Does "test this please" work for this repo? @fbricon

**Comment by fbricon** [comment]
no that command is for jenkins only. If you click on the Details link for the Travis check, you'll reach https://travis-ci.org/redhat-developer/vscode-java/builds/557822514?utm_source=github_status&utm_medium=notification and can manually trigger a rebuild

**Comment by fbricon** [comment]
The PR consistently fails to build on Travis. Also, I'm unable to rebase against master

**Comment by akaroml** [comment]
> The PR consistently fails to build on Travis. Also, I'm unable to rebase against master

The test was just fixed. There were path issues before the fix. Let me try to rebase.

**Comment by akaroml** [comment]
Done rebasing. should be fine to merge now. @fbricon

**Comment by fbricon** [comment]
Thanks @akaroml !

**Pull request merged**
