### PR TITLE
Check onDidCreateFiles is available

### LINKED ISSUE #1363: Failure to start 0.59 in theia 1.0.0/dev - onDidCreateFiles is not a function in workspace
Failure to load vscode-java plugin from https://github.com/redhat-developer/vscode-java after installation, see logs.

##### Environment
- Operating System: Ubuntu/Linux 18.04
- JDK version: 1.8.0.u242
- Visual Studio Code version: Theia 1.0.0 and Theia dev@5e45d2b8a
- Java extension version: 0.59.0 https://github.com/redhat-developer/vscode-java

##### Steps To Reproduce
1. Install the java extension from RedHat using plugin manager.
2. Restart Theia and check the logs or get an alert in the workspace.

```
root INFO [hosted-plugin: 15127] PLUGIN_HOST(15127): PluginManagerExtImpl/loadPlugin(/home/robdu/.theia/extensions/redhat.java-0.59.0/extension/dist/extension)
root INFO [hosted-plugin: 15127] { message:
   'Starting Java server with: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/robdu/.theia/extensions/redhat.java-0.59.0/extension/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/robdu/.theia/globalStorage/redhat.java/0.59.0/config_ss_linux -data /home/robdu/.theia/workspace-storage/be4182b2fd4f02a250118b10cb0727ab/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2020-04-03 10:49:17.326' }
root INFO [hosted-plugin: 15127] { message:
   'Starting Java server with: /usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -noverify -jar /home/robdu/.theia/extensions/redhat.java-0.59.0/extension/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/robdu/.theia/globalStorage/redhat.java/0.59.0/config_linux -data /home/robdu/.theia/workspace-storage/be4182b2fd4f02a250118b10cb0727ab/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2020-04-03 10:49:17.341' }
root ERROR [hosted-plugin: 15127] Error on activation of java TypeError: s.workspace.onDidCreateFiles is not a function
    at Object.t.registerFileEventHandlers (/home/robdu/.theia/extensions/redhat.java-0.59.0/extension/dist/extension.js:7:96930)
    at Promise (/home/robdu/.theia/extensions/redhat.java-0.59.0/extension/dist/extension.js:1:196948)
    at new Promise (<anonymous>)
    at /home/robdu/.theia/extensions/redhat.java-0.59.0/extension/dist/extension.js:1:188258
    at Generator.next (<anonymous>)
    at o (/home/robdu/.theia/extensions/redhat.java-0.59.0/extension/dist/extension.js:1:180810)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

##### Current Result

The plugin fails to activate.

##### Expected Result

The plugin activates without any errors and code completion for Java works.

##### Additional Informations

-

### PR DESCRIPTION
**Pull request by fbricon**
Fixes #1363

### CODE REVIEW

**Comment by fbricon** [comment]
@codingchili can you test this PR on Theia? cc @akosyakov

**Comment by codingchili** [comment]
@fbricon tested, the plugin now starts in 1.0.0. Many thanks for a very quick fix.

**Comment by akosyakov** [comment]
I hope we fix it soon in Theia.

**Comment by fbricon** [comment]
0.59.1 was published to both the VS Code Marketplace and https://open-vsx.org/extension/redhat/java

**Pull request merged**
