### PR TITLE
Turn off text edit lazy resolving

### PR DESCRIPTION
**Pull request by jdneo**
Turn off the lazy resolve flag due to https://github.com/microsoft/vscode/pull/183224.

@rgrunber, I suggest that we arrange a pre-release only containing this change. Then we can observe the impact on the perf using that specific version. The data can also be used for some analysis and discussion.

### CODE REVIEW

**Review by rgrunber — APPROVED** [review]
We just merged some changes with performance implications but they would be included in [`1.19.2023052504`](https://redhat.gallerycdn.vsassets.io/extensions/redhat/java/1.19.2023052504/1685002458002/Microsoft.VisualStudio.Code.Manifest) (it includes the `java.edit.validateAllOpenBuffersOnChanges` property.

We could merge this for tomorrow (or even now) and it would be separate from those.

**Comment by jdneo** [comment]
Thank you @rgrunber, looks good.

**Comment by rgrunber** [comment]
Appears to be an infrastructure issue. It's waiting for an appropriate node but they're all offline :|

**Comment by rgrunber** [comment]
`v1.19.2023053001` should contain the this change.

**Comment by jdneo** [comment]
Thank you @rgrunber !

**Pull request merged**
