### PR TITLE
Support "textDocument/selectionRange"

### LINKED ISSUE #780: Support semantic selection
Support the new semantic selection

Refs
Semantic selections: https://github.com/Microsoft/vscode/issues/4795
LSP: https://github.com/Microsoft/language-server-protocol/issues/613

### PR DESCRIPTION
**Pull request by akaroml**
Fix #780

### CODE REVIEW

**Comment by Eskibear** [comment]
Suggest to follow [migration guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode)  to use `@types/vscode` instead of `vscode`

**Comment by akaroml** [comment]
> Suggest to follow [migration guide](https://code.visualstudio.com/api/working-with-extensions/testing-extension#migrating-from-vscode) to use `@types/vscode` instead of `vscode`

This to me is like changing the way we reference vscode module for the purpose of TESTING. It's worth a separate issue and PR for visibility. Please help create an issue stating the cause.

**Comment by Eskibear** [comment]
`@types/vscode` migration is tracked in #977

**Comment by akaroml** [comment]
> Please expose the new preference in package.json and update the readme.md, listing the new feature and the new preference key in the `new in 0.47.0` paragraph

Nice reminders. Will do!

**Pull request merged**
