### PR TITLE
Register the semantic token provider after standard server is ready

### PR DESCRIPTION
**Pull request by jdneo**
@Eskibear I delay the registration to the standard server ready event. Please take a look.

Signed-off-by: Sheng Chen <sheche@microsoft.com>

### CODE REVIEW

**Comment by Eskibear** [comment]
LGTM

**Comment by fbricon** [comment]
please resolve the conflict

**Comment by jdneo** [comment]
Updated

**Comment by fbricon** [comment]
@jdneo thanks!

**Pull request merged**
