### PR TITLE
Disable completion limit

### PR DESCRIPTION
**Pull request by fbricon**
following https://github.com/redhat-developer/vscode-java/pull/1503, we can set java.completion.maxResults to a much larger value.

### CODE REVIEW

**Comment by fbricon** [comment]
@Eskibear @jdneo @testforstephen wdyt?

**Comment by jdneo** [comment]
Or maybe just use `0`?

**Comment by Eskibear** [comment]
0 should be fine. 2000 doesn't solve the inconvinience brought by the "incomplete list" approach, like in #1276
Known max value for a typical project (spring-petclinic) is ~3000, with the 2000 limit I don't feel the difference, in both case there's a little bit lagging like hundreds of ms.

2000 is indeed a safe choice for large projects with more packages and classes (e.g. >10K candidates). We can change the description to tell users, they can set the limit for better performance but in trade of completeness. 

The more the number is, the more cases where it gives a complete list. I'm ok with both, but prefer 0(infinite) for simplicity and less confusion. Then we only need to explain one thing:
* When users get bad perf for extremely large projects, we point them to the setting.

Otherwise we'll also have to explain why the completion list **sometimes** is incomplete.

**Comment by fbricon** [comment]
Ok, set limit to 0 (aka ∞)

**Pull request merged**
