### PR TITLE
Move to Java 17

### PR DESCRIPTION
**Pull request by snjeza**
Requires https://github.com/eclipse/eclipse.jdt.ls/pull/2118

Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
Thanks for doing this. There's also a reference inside `pr-verify.yml` that should be updated. I'm not sure about `.sdkmanrc` but I suspect that as well. May need to figure out what the proper version is through there.

**Comment by snjeza** [comment]
> There's also a reference inside pr-verify.yml

Fixed.

**Comment by snjeza** [comment]
test this please

**Comment by rgrunber** [comment]
Can we also just change the `.sdkmanrc` to contain `17.0.3-tem` . I think that should be the version from Adoptium. Otherwise, I think this is ready to be merged.

**Comment by rgrunber** [comment]
We should also update https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements on the wiki page once this is merged.

**Comment by snjeza** [comment]
> Can we also just change the .sdkmanrc to contain 17.0.3-tem . I think that should be the version from Adoptium. Otherwise, I think this is ready to be merged.

@rgrunber I have updated the PR.

**Review by rgrunber — APPROVED** [review]

**Comment by snjeza** [comment]
> We should also update https://github.com/redhat-developer/vscode-java/wiki/JDK-Requirements on the wiki page once this is merged.

@rgrunber I have updated it.

**Comment by afriza** [comment]
Which last extension version supports < JavaSE-17 ? v1.7.0?
Because of extension auto-update, I get the install JDK 17 prompt.

**Comment by rgrunber** [comment]
> Which last extension version supports < JavaSE-17 ? v1.7.0? Because of extension auto-update, I get the install JDK 17 prompt.

Yes, 1.7.0 would be the last version that can be started with a Java runtime less than version 17.

**Pull request merged**
