### PR TITLE
Adopt the Lombok 1.18.33 edge release.

### PR DESCRIPTION
**Pull request by marco-belonio**
https://github.com/redhat-developer/vscode-java/issues/3561

### CODE REVIEW

**Comment by blizzy78** [comment]
But edge != latest version?

**Comment by sleberknight** [comment]
From the [Downloads](https://projectlombok.org/download) page, it looks like you can use the generic link:

https://projectlombok.org/downloads/lombok.jar

I am _assuming_ (but don't know for sure) that this link will always get the latest stable version. As of right now, that is 1.18.32 - the link text is _Download 1.18.32_

So maybe just need to use this link and then will always get the most recent stable version?

**Comment by rgrunber** [comment]
Thanks for getting this started. I remember when the original issue was filed but didn't see any progress for a long while.

Could you make the change look like the gulpfile at https://github.com/redhat-developer/vscode-java/commit/b59c43a2f7e5c2963084d8f7c6f55ade50e8cd02#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7 ? This won't require changing any runtime code. Instead of `1.18.31` (the unreleased version that "edge" was targetting then), call it `1.18.33`.

If the edge release contains a fix, we can definitely adopt.

**Comment by marco-belonio** [comment]
@sleberknight The problem is, that the 1.18.32 does not work to resolve the problem :S

**Comment by sleberknight** [comment]
> @sleberknight The problem is, that the 1.18.32 does not work to resolve the problem :S

Oops. Sorry! Clearly I missed that important part.

**Pull request merged**
