### PR TITLE
Show the error status when imported projects having errors

### PR DESCRIPTION
**Pull request by jdneo**
requires https://github.com/eclipse/eclipse.jdt.ls/pull/1962

Signed-off-by: Sheng Chen <sheche@microsoft.com>

### CODE REVIEW

**Comment by rgrunber** [comment]
Using https://github.com/spring-projects/spring-boot, this doesn't seem to work for me as I'd expect. I've built the JDT-LS change along with this change, but even with breakpoints on the [`Error`](https://github.com/redhat-developer/vscode-java/blob/f505f60d74abecbdd7bd290ff6549406c870c484/src/standardLanguageClient.ts#L117) case in the client, or at the [`GradleProjectImporter`](https://github.com/eclipse/eclipse.jdt.ls/blob/62f20895b67378327df9081742c2812c63651a47/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/GradleProjectImporter.java#L201) in the server, nothing is triggered.

The import of does result in some errors reported in the problems tab, but the thumbs up (ServiceReady) is also shown.

**Comment by jdneo** [comment]
@rgrunber did you also adopt the PR at the LS side? https://github.com/eclipse/eclipse.jdt.ls/pull/1962

**Review by rgrunber — APPROVED** [review]
It turns out my problem was the project likely built and all I was seeing were compilation errors. I introduced an issue in the build file and this allowed me to see this change works.

**Comment by jdneo** [comment]
@rgrunber This PR is still use the stable API to show the status when project configuration has errors.

It use 👎(same as when server crash) when project configuration has errors. Or maybe a ⚠️ icon will be better?

**Review by testforstephen — APPROVED** [review]
LGTM

**Pull request merged**
