### PR TITLE
A command for invoking rename action

### PR DESCRIPTION
**Pull request by gorkem**
Adds a new command that invokes the rename action of the
editor.

requires https://github.com/eclipse/eclipse.jdt.ls/pull/430

### CODE REVIEW

**Comment by fbricon** [comment]
It doesn't work for method renames:

nov-15-2017 11-12-03

In Eclipse, method renaming is not propagated.

**Comment by gorkem** [comment]
Yes. same behavior also on Fields too. Our rename logic is not handling it correctly, regardless of this PR. I think I will handle that separately.

**Comment by fbricon** [comment]
Instead of returning a rename command, it'll be easier to return a textedit with the new name instead (possibly as a `${newName}` placeholder.

**Comment by gorkem** [comment]
That would not work. It is the same situation it would be same experience as extract method code action as we have it today.  You would have to invoke a separate rename operation to correct it. Also what is the point of avoiding the rename command?

**Comment by fbricon** [comment]
If there are duplicates, it's impossible to know if the duplicate you're fixing needs to see its name change propagated. Eclipse is inconsistent there. for local variables, renaming is propagated, but not for methods.
So if rename is just for the current selection (like for methods), it doesn't need the full blown rename process. We could make it behave the same for variables, for consistency purposes.

It really depends on what we're expecting from a duplicate code action. Once we settle on a behaviour, it'll narrow down our options.

**Comment by gorkem** [comment]
The inconsistency is on the rename process, it needs to be fixed on the rename operation. The behavior of invoking the rename action is the correct one, IMHO.

**Comment by gorkem** [comment]
closing, as this functionality is no longer needed

**Pull request closed without merging**
