### PR TITLE
Provide support for Java 21

### LINKED ISSUE #3292: Provide support for Java 21
The related Eclipse PR - https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1325
[Java 21 support](https://www.eclipse.org/lists/jdt-dev/msg02289.html)
[Java 21 Marketplace entry](https://marketplace.eclipse.org/content/java-21-support-eclipse-2023-09-429)

### PR DESCRIPTION
**Pull request by snjeza**
Fixes #3292 
Requires https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2863
Test vsix - [VS Code 1.24.5](https://github.com/snjeza/vscode-test/raw/master/java-1.24.5.vsix)

### CODE REVIEW

**Comment by blaumeise20** [comment]
This might be a stupid comment, but please add support for this soon! I really need it for work and it blocks me otherwise. I already tried using the test extension linked in this PR, but sadly I am getting TONS of "Unbound classpath container" errors.

**Comment by blaumeise20** [comment]
I did actually try your extension but it for some reason didn't work. I even deleted the entire old extension manually in the .vscode folder and installed the one you linked, but without success. It stays at JavaSE-17 for me, even though I explicitly set the default to JavaSE-21 in the settings.

**Comment by snjeza** [comment]
@blaumeise20 Could you try [VS Code 1.24.7](https://github.com/snjeza/vscode-test/raw/master/java-1.24.7.vsix)?
Could you attach a project example?

**Comment by cypher256** [comment]
@snjeza 
The package.json for 1.24.7 does not contain "JavaSE-21", is this correct?
```json
    "version": "1.24.7",
    ---
						"properties": {
							"name": {
								"type": "string",
								"enum": [
									"J2SE-1.5",
									"JavaSE-1.6",
									"JavaSE-1.7",
									"JavaSE-1.8",
									"JavaSE-9",
									"JavaSE-10",
									"JavaSE-11",
									"JavaSE-12",
									"JavaSE-13",
									"JavaSE-14",
									"JavaSE-15",
									"JavaSE-16",
									"JavaSE-17",
									"JavaSE-18",
									"JavaSE-19",
									"JavaSE-20"
								],
```

**Comment by blaumeise20** [comment]
I just figured out the same, yeah.

**Comment by blaumeise20** [comment]
I tried the new version now and it is still stuck at 
Bildschirmfoto 2023-10-11 um 09 00 54
I still get all the same errors. Project links resolve correctly and I get hover information and everything, but it can't resolve any of the standard library items like `Object` or `String`.
Bildschirmfoto 2023-10-11 um 09 03 06
And in the very top I get the weirdest error:
Bildschirmfoto 2023-10-11 um 09 03 36

**Comment by snjeza** [comment]
@blaumeise20 @cypher256 Could you please try [VS Code 1.25.1](https://github.com/snjeza/vscode-test/raw/master/java-1.25.1.vsix) ?

**Comment by aghasemi** [comment]
> @blaumeise20 @cypher256 Could you please try [VS Code 1.25.1](https://github.com/snjeza/vscode-test/raw/master/java-1.25.1.vsix) ?

Hello. This worked for me (on Code Server). Many thanks. However, the `STR` object used in String templates is still missing, it seems.

**Comment by snjeza** [comment]
> However, the STR object used in String templates is still missing, it seems.

@aghasemi You may want to take at https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2863#issuecomment-1734912969

**Comment by cypher256** [comment]
Java 21 worked correctly on 1.25.1. Excellent!

**Comment by blaumeise20** [comment]
I tried it with the version you provided and it still doesn't work correctly.

I can't provide an example because it is a 15-year-old company project with thousands of files, but I can show you a part of the .classpath file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" path="src"/>
    <classpathentry kind="src" path="src_gen"/>
    ...
    <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/jdk-21">
        <attributes>
            <attribute name="module" value="true"/>
        </attributes>
    </classpathentry>
    ...
</classpath>
```

**Comment by blaumeise20** [comment]
It turned out I just had to change `jdk-21` to `JavaSE-21` and everything worked...

**Comment by slymon99** [comment]
Getting errors with 1.25.1 on tons of imports as well as on certain interface implementations (The type xyz must implement the inherited abstract method blah). Standard (but very large) gradle project that works on Java 17.

Screenshot 2023-10-12 at 1 50 22 PM

LSP log has errors that look like
```
!ENTRY org.eclipse.jdt.ls.core 4 2 2023-10-12 13:48:39.495
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 0
org.eclipse.buildship.core.internal.GradlePluginsRuntimeException: Model not available for algo
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:82)
	at org.eclipse.buildship.core.internal.workspace.GradleClasspathContainerRuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(GradleClasspathContainerRuntimeClasspathEntryResolver.java:58)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathEntryResolver.resolveRuntimeClasspathEntry(RuntimeClasspathEntryResolver.java:49)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1261)
	at org.eclipse.buildship.core.internal.launch.GradleClasspathProvider.resolveClasspath(GradleClasspathProvider.java:101)
	at org.eclipse.jdt.internal.launching.RuntimeClasspathProvider.resolveClasspath(RuntimeClasspathProvider.java:68)
	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1663)
	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspathAndModulepath(AbstractJavaLaunchConfigurationDelegate.java:464)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand$1.run(ProjectCommand.java:176)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2453)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2478)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspathsFromJavaProject(ProjectCommand.java:173)
	at org.eclipse.jdt.ls.core.internal.commands.ProjectCommand.getClasspaths(ProjectCommand.java:153)
	at org.eclipse.jdt.ls.core.internal.JDTDelegateCommandHandler.executeCommand(JDTDelegateCommandHandler.java:95)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:230)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:614)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by snjeza** [comment]
@slymon99 Could you try to update to the 8.4 version of gradle? See https://docs.gradle.org/current/userguide/compatibility.html

**Comment by slymon99** [comment]
I am on gradle 8.4 already

```
$ ../gradlew -version

------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-04 20:52:13 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          21 (Amazon.com Inc. 21+35-LTS)
OS:           Linux 6.2.0-1012-aws amd64
```

**Comment by snjeza** [comment]
Could you attach a project example?

**Comment by cypher256** [comment]
Note: vscode-gradle feat(jdk): Support JDK21
https://github.com/microsoft/vscode-gradle/pull/1419

**Comment by snjeza** [comment]
> I am on gradle 8.4 already

This is an upstream [buildship](https://github.com/eclipse/buildship) issue. buildship doesn't support JDK 21/gradle 8.4

**Comment by slymon99** [comment]
> > I am on gradle 8.4 already
> 
> This is an upstream [buildship](https://github.com/eclipse/buildship) issue. buildship doesn't support JDK 21/gradle 8.4

Created an issue upstream https://github.com/eclipse/buildship/issues/1271. Not sure if this blocks this release, is gradle support implicitly part of the LSP?

**Comment by snjeza** [comment]
> Not sure if this blocks this release

No, it doesn't block this PR. Only Gradle projects that use JDK 21/Gradle 8.4 will not work.

**Pull request merged**
