### PR TITLE
Only enable organize imports command in java files

### LINKED ISSUE #473: Organize imports should not be active in non-java files
The Java organize imports command should only be active in java files

##### Environment
- Java extension version: Latest

##### Steps To Reproduce
1. Open a md file
2. Try pressing shift+alt+o

##### Current Result
Error about `'java.edit.organizeImports' not found`

##### Expected Result
No action. This command should only be registered for java files

### PR DESCRIPTION
**Pull request by mjbvz**
Fixes #473

### CODE REVIEW

**Comment by fbricon** [comment]
@mjbvz thanks for the patch! 
But can you please sign-off your commit before we can merge it?

**Comment by mjbvz** [comment]
Done

**Comment by fbricon** [comment]
the organize import command is no longer available in the command palette even though the current editor is a java file

screen shot 2018-03-20 at 1 57 16 pm

**Comment by fbricon** [comment]
Works as advertised now, thanks for the fix @mjbvz!

**Pull request merged**
