### PR TITLE
server task sorting issue fix

### PR DESCRIPTION
**Pull request by priyangbhavsar**
- fixed the sorting logic of server tasks

- issue :  #2627

### CODE REVIEW

**Review by datho7561 — APPROVED** [review]
Yes, this works great! Now when you load in a large project (such as eclipse.jdt.ls), it's much easier to keep track of the progress. Thanks @priyangbhavsar !

**Comment by fbricon** [comment]
@datho7561 can you share a gif showing before/after the change?

**Comment by datho7561** [comment]
Old: the progress is usually at the top but not always:

progress-at-top-but-not-always

New: the progress is always on the bottom:

progress-at-bottom

**Comment by fbricon** [comment]
well the code explictly says "// make sure in-progress items are always at the end"
@akaroml any particular reason to do so?

**Comment by rgrunber** [comment]
Maybe there was some point when the terminal had auto-scrolling issues ? I could see wanting to place in-progress items at the top in that case. However, having them at the bottom is a huge improvement. I think we can merge after tomorrow's release.

**Comment by mozhuanzuojing** [comment]
great

**Pull request merged**
