### PR TITLE
Change minimum JDK requirement since platform specific extension is released

### PR DESCRIPTION
**Pull request by nickzhums**

### CODE REVIEW

**Comment by nickzhums** [comment]
@rgrunber @testforstephen @Eskibear

**Comment by Eskibear** [comment]
@nickzhums  `-s` is required when you `git commit`, in order to pass DCO.

**Comment by testforstephen** [comment]
@nickzhums could you rebase your commit?

**Comment by nickzhums** [comment]
just did. could you check? @testforstephen

**Review by akaroml — APPROVED** [review]
LGTM!

**Review by testforstephen — APPROVED** [review]
LGTM

**Pull request merged**
