### PR TITLE
Start server with -Dfile.encoding=[vscode file encoding (UTF-8)] by default

### PR DESCRIPTION
**Pull request by fbricon**
Candidate fix for #788

### CODE REVIEW

**Comment by fbricon** [comment]
While that patch would fix #788 (and other similar reports in the past), by forcing the server to run with  UTF-8 instead of the platform's default encoding, I'm actually not sure about the potential drawbacks of that approach. Users can still set the -Dfile.encoding flag in jdt.ls.vmargs, but I don't know how many people would see a regression with the new default behavior.

**Comment by tsmaeder** [comment]
In think the default should be the default from the machine where the source code lives. The language server cannot determine that, since it can be used in many different settings.

**Comment by tsmaeder** [comment]
@fbricon what do you get when you ask for the default encoding from a Java program? Second, there are already provisions for overriding the default encoding in Eclipse. Maybe we should just surface them?

**Comment by fbricon** [comment]
Funny thing is when I display Charset.defaultCharset() when the server start, I get US-ASCII. But when I run `locale` in a terminal I have:
```
LANG="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_CTYPE="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_ALL=
```  
I have no idea why or what sets my jdt.ls to use US-ASCII. If I run a Java program from vscode, it returns UTF-8.
I like the idea of reusing vscode's default encoding.
As for exposing the server's encoding from props, I need to look into it (I also got an unfinished WIP on source encoding, but got stuck on the client side because I couldn't use a modifiable list).

**Comment by fbricon** [comment]
Updated PR to send vscode's default encoding settings for Java (or global files.encoding -utf8 by default- if nothing is set)

**Pull request merged**
